Repository JNU-econovation/MacMorning-FE, pull requests merged in 2025-07, with the labels that each got.

#55 feat: 선택지 선택 버튼 구현
  src/apis/book/getBooks.ts
  src/apis/story/storyProgress.ts
  src/components/storyProgress/SelectButton.tsx
  src/constants/api.ts
  src/pages/createBook/selectView/StorySettingView.tsx
  src/types/form.d.ts
Labels: feature

#93 feat: 로딩 컴포넌트 구현
  src/components/common/loading/Loading.tsx
Labels: feature

#97 feat : 동화책 열람 페이지 구현
  App.tsx
  src/apis/book/getBook.ts
  src/components/common/book/BookComponent.tsx
  src/components/common/buttons/ShareButton.tsx
  src/components/common/buttons/StepButton.tsx
  src/hooks/useImageUrl.ts
  src/pages/readBook/ReadBook.tsx
  src/pages/readBook/ReadBookView.tsx
  src/pages/shareBook/ShareBook.tsx
  src/types/book.d.ts
  src/types/navigation.d.ts
  src/utils/navigate/NavigateHelpers.tsx
Labels: feature

#103 feat : 동화책 열람 페이지 모달창 구현
  src/assets/images/common/menu-black.svg
  src/components/common/header/EditButton.tsx
  src/components/common/header/EditModal.tsx
  src/pages/readBook/ReadBook.tsx
  src/pages/readBook/ReadBookView.tsx
Labels: feature

#108 feat: 다음 이야기 진행 구현
  src/apis/story/storyProgress.ts
  src/pages/storyProgress/StoryProgress.tsx
  src/pages/storyProgress/StoryProgressView.tsx
Labels: feature

#113 refactor: 이야기 생성 시 페이지 이동 불가능 설정
  src/components/common/header/BackButton.tsx
  src/components/common/header/Header.tsx
  src/pages/storyProgress/StoryProgress.tsx
  src/pages/storyProgress/StoryProgressView.tsx
Labels: refactor

#118 fix : 이미지 삽입 / 이미지 생성 후 이미지 보여주기 기능 수정
  android/app/src/main/AndroidManifest.xml
  src/apis/AI/createImage.ts
  src/apis/upload/imageUpload.ts
  src/constants/domain.ts
  src/hooks/useImageUrl.ts
  src/pages/ChooseThumbnail/ChooseThumbnailView.tsx
  src/pages/readBook/ReadBookView.tsx
  src/pages/storyProgress/StoryProgress.tsx
  src/pages/storyProgress/StoryProgressView.tsx
  src/utils/ImagePicker.ts
Labels: bug

#124 feat: 이메일 및 비밀번호 형식 vlidator 적용
  src/pages/auth/signin/PasswordErrorView.tsx
  src/pages/auth/signin/Signin.tsx
  src/pages/auth/signin/ValidateView.tsx
  src/utils/validator/validator.tsx
Labels: feature

#121 feat: image patch 구현 및 적용
  src/apis/questions/getQuestions.tsx
  src/apis/story/storyProgress.ts
  src/apis/upload/imageUpload.ts
  src/pages/storyProgress/StoryProgress.tsx
  src/pages/storyProgress/StoryProgressView.tsx
  src/types/form.d.ts
Labels: feature

#129 feat: 찜하기 기능 구현
  src/apis/book/likeBook.ts
  src/components/common/book/BookComponent.tsx
  src/components/common/buttons/LikeButton.tsx
  src/types/book.d.ts
Labels: feature

#130 feat: 질문 답변 저장
  src/apis/questions/getQuestions.tsx
  src/pages/questions/Questions.tsx
  src/pages/questions/QuestionsTitle.tsx
  src/types/form.d.ts
Labels: feature

#148 bug: 질문이 없을 때의 예외 처리
  src/pages/questions/Questions.tsx
Labels: bug

#149 bug: 이야기 읽기 내 돌아가기 버튼 미동작
  src/pages/questions/ReadQuestions.tsx
Labels: bug
